### PR TITLE
Fix issue #3

### LINKED ISSUE #3: Update entry to not check for file existance
From @sokra [on gitter](https://gitter.im/webpack/webpack?at=56c4229e5fa70a130ea50d91):

> @kentcdodds Looks good. The entry validator should not check for file existance, as the string is resolved, which means you can omit extension, add query parameters, add loaders, use modules paths. This is disallowed when checking of file existance.

Basically doing this validation thing is going to be really hard because Webpack is amazingly flexible.

### PR DESCRIPTION
**Pull request by jonathanewerner**
This fixes #3. In light of the multitude of possibilities for valid input strings i opted to just check for strings / strings in arrays / strings|arrays in object values.

### CODE REVIEW

File: src/validators/entry/index.js [hunk 1]
```diff
@@ -11,26 +9,17 @@ export default {
...
+    return null
+  } else if (isArray(val) || isObject(val)) {
+    return map(val, entry => validateEntry(entry, {config}))
       .filter(error => error)
-      .join(' - ')
-  } else if (isObject(val)) {
-    return map(val, entryVal => validateEntry(entryVal, {config}))
-      .filter(error => error)
-      .join(' - ')
+      .join('\n')
```
Comment (kentcdodds) [inline src/validators/entry/index.js]: Curious why you changed this from ` - ` to `\n`. I would worry that it would make the output confusing (which is normally one line per error/warning).

File: tests/passing-configs/pac.development.js [hunk 2]
```diff
@@ -0,0 +1,2 @@
+import {makeConfig} from './pac.production';
+export default makeConfig({production: false});
```
Comment (kentcdodds) [inline tests/passing-configs/pac.development.js]: :+1: good approach

File: src/validators/entry/index.js [hunk 3]
```diff
@@ -1,9 +1,7 @@
-import path from 'path'
 import {
   isString, isArray,
   isObject, map,
 } from 'lodash'
-import {fileExists} from '../../utils'
```
Comment (kentcdodds) [inline src/validators/entry/index.js]: I don't think anything else uses this util function, and it's kind of a mess anyway. Care to remove it and its tests? :+1:

**Comment by kentcdodds** [comment]
Left a few comments. This is awesome. Thanks! :+1:

File: src/validators/entry/index.js (hunk 3 above)
Comment (jonathanewerner) [inline src/validators/entry/index.js]: Yep, will do.

File: src/validators/entry/index.js (hunk 1 above)
Comment (jonathanewerner) [inline src/validators/entry/index.js]: Ok, wasn't aware of the one line per error thing. Will probably revert this behaviour then.

**Comment by jonathanewerner** [comment]
@kentcdodds Fixed those things.

**Comment by kentcdodds** [comment]
LGTM! Could we get one more reviewer on this? Feel free to hit the green button if it looks good to you!

**Comment by sarbbottam** [comment]
nice :red_circle: PR :+1:
